name: Deploy Astro to Pages

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            PUBLIC_SITE_NAME: ${{ secrets.PUBLIC_SITE_NAME }}
            SITE_URL: ${{ secrets.SITE_URL }}
            BASE_PATH: ${{ secrets.BASE_PATH }}

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: pnpm
            - run: pnpm install --frozen-lockfile=false
            - name: Create .env file
              run: |
                  echo "PUBLIC_SITE_NAME=${{ env.PUBLIC_SITE_NAME }}" >> .env
                  echo "SITE_URL=${{ env.SITE_URL }}" >> .env
                  echo "BASE_PATH=${{ env.BASE_PATH }}" >> .env

            - name: Build
              run: pnpm run build
              env:
                  SITE_URL: https://gamble.nexusgit.info
                  GITHUB_PAGES: "true"
            - uses: actions/upload-pages-artifact@v3
              with:
                  path: dist
    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - id: deployment
              uses: actions/deploy-pages@v4
